### ISSUE TITLE
Colab for dreambooth stopped working

### ISSUE THREAD

**Issue by Instantexit** [TheLastBen/fast-stable-diffusion#102] opened 2022-10-07 14:17 UTC
The colab stopped working for some reason for me and others. I get this as the last message before it stops:

  raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/stable-diffusion-v1-4', '--instance_data_dir=/content/data/joda', '--class_data_dir=/content/data/dog', '--output_dir=/content/models/joda', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of a joda dog', '--class_prompt=photo of a dog', '--seed=11111', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=1000', '--num_class_images=200']' returned non-zero exit status 1.
Something went wrong

It was working fine a day ago, and I did not change anything.... Any ideas?

**Comment by TheLastBen** [comment] 2022-10-07 14:24
disconnect the runtime and reconnect, if the same error copy the whole log

**Comment by TheLastBen** [comment] 2022-10-07 14:25
if the problem persists, try generating the class images externally then use the input path to specify the folder

**Comment by seang** [comment] 2022-10-09 03:41
I started getting this too with no config changes, fwiw locking these two dependencies to specific versions during install stabilized it for me:

```
!pip install git+https://github.com/TheLastBen/diffusers.git@916754ea5e053c2d3af7efe22ef12475e73488ab
%pip install accelerate===0.12.0
```

**Comment by TheLastBen** [comment] 2022-10-09 03:47
The issue is fixed in the latest colab, update it for a better experience

**Closed** 2022-10-10 18:53 UTC
