### ISSUE TITLE
A100 Support

### ISSUE THREAD

**Issue by delbalso** [TheLastBen/fast-stable-diffusion#27] opened 2022-09-30 23:24 UTC
What can I do to help get a100 support?

**Comment by TheLastBen** [comment] 2022-09-30 23:26
Thanks,

run :

`!pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`

after around 40min, and the installation is done, navigate to /usr/local/lib/python3.7/dist-packages/xformers

save the two files : "_C_flashattention.so" and "_C.so", upload them to any host and send me the link and I will integrate them.

the files might not show in the colab explorer, so you will have to rename them

```
!cp /usr/local/lib/python3.7/dist-packages/xformers/_C.so /usr/local/lib/python3.7/dist-packages/xformers/C.py

!cp /usr/local/lib/python3.7/dist-packages/xformers/_C_flashattention.so /usr/local/lib/python3.7/dist-packages/xformers/C_flashattention.py
```

**Comment by delbalso** [comment] 2022-10-01 05:30
https://file.io/UkvT0KEU31MY
kept them as .py files

**Comment by delbalso** [comment] 2022-10-01 05:36
The notebook still doesn't work though. I get this error.

> The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `6` to improve out-of-box performance
> To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
> Downloading: 100% 543/543 [00:00<00:00, 565kB/s]
> Fetching 16 files:   0% 0/16 [00:00<?, ?it/s]
> Downloading: 100% 342/342 [00:00<00:00, 359kB/s]
> Fetching 16 files:   6% 1/16 [00:00<00:11,  1.36it/s]
> Downloading: 100% 4.56k/4.56k [00:00<00:00, 3.96MB/s]
> Fetching 16 files:  19% 3/16 [00:01<00:05,  2.31it/s]
> Downloading:   0% 0.00/1.22G [00:00<?, ?B/s]
> Downloading:   0% 4.71M/1.22G [00:00<00:25, 47.1MB/s]
> Downloading:   1% 12.3M/1.22G [00:00<00:18, 64.2MB/s]
> Downloading:   2% 19.9M/1.22G [00:00<00:17, 69.4MB/s]
> Downloading:   2% 27.5M/1.22G [00:00<00:16, 72.0MB/s]
> Downloading:   3% 35.1M/1.22G [00:00<00:16, 73.6MB/s]
> Downloading:   4% 42.8M/1.22G [00:00<00:15, 74.5MB/s]
> Downloading:   4% 50.4M/1.22G [00:00<00:15, 75.2MB/s]
> Downloading:   5% 58.0M/1.22G [00:00<00:15, 75.5MB/s]
> Downloading:   5% 65.6M/1.22G [00:00<00:15, 74.5MB/s]
> Downloading:   6% 73.1M/1.22G [00:01<00:15, 74.8MB/s]
> Downloading:   7% 80.8M/1.22G [00:01<00:15, 75.2MB/s]
> Downloading:   7% 88.4M/1.22G [00:01<00:14, 75.5MB/s]
> Downloading:   8% 96.0M/1.22G [00:01<00:14, 75.7MB/s]
> Downloading:   9% 104M/1.22G [00:01<00:14, 75.8MB/s] 
> Downloading:   9% 111M/1.22G [00:01<00:14, 76.1MB/s]
> Downloading:  10% 119M/1.22G [00:01<00:14, 76.0MB/s]
> Downloading:  10% 127M/1.22G [00:01<00:14, 76.0MB/s]
> Downloading:  11% 134M/1.22G [00:01<00:14, 76.3MB/s]
> Downloading:  12% 142M/1.22G [00:01<00:14, 75.4MB/s]
> Downloading:  12% 149M/1.22G [00:02<00:14, 75.6MB/s]
> Downloading:  13% 157M/1.22G [00:02<00:13, 75.8MB/s]
> Downloading:  14% 165M/1.22G [00:02<00:13, 76.0MB/s]
> Downloading:  14% 172M/1.22G [00:02<00:13, 76.3MB/s]
> Downloading:  15% 180M/1.22G [00:02<00:13, 76.3MB/s]
> Downloading:  15% 188M/1.22G [00:02<00:13, 76.2MB/s]
> Downloading:  16% 195M/1.22G [00:02<00:13, 76.4MB/s]
> Downloading:  17% 203M/1.22G [00:02<00:13, 76.4MB/s]
> Downloading:  17% 211M/1.22G [00:02<00:13, 76.5MB/s]
> Downloading:  18% 218M/1.22G [00:02<00:13, 76.5MB/s]
> Downloading:  19% 226M/1.22G [00:03<00:12, 76.4MB/s]
> Downloading:  19% 234M/1.22G [00:03<00:12, 76.2MB/s]
> Downloading:  20% 241M/1.22G [00:03<00:12, 76.4MB/s]
> Downloading:  20% 249M/1.22G [00:03<00:12, 76.3MB/s]
> Downloading:  21% 257M/1.22G [00:03<00:12, 76.4MB/s]
> Downloading:  22% 264M/1.22G [00:03<00:12, 76.5MB/s]
> Downloading:  22% 272M/1.22G [00:03<00:12, 76.4MB/s]
> Downloading:  23% 280M/1.22G [00:03<00:12, 76.2MB/s]
> Downloading:  24% 287M/1.22G [00:03<00:12, 76.3MB/s]
> Downloading:  24% 295M/1.22G [00:03<00:12, 76.0MB/s]
> Downloading:  25% 303M/1.22G [00:04<00:12, 75.2MB/s]
> Downloading:  26% 310M/1.22G [00:04<00:11, 75.6MB/s]
> Downloading:  26% 318M/1.22G [00:04<00:11, 75.8MB/s]
> Downloading:  27% 325M/1.22G [00:04<00:11, 75.7MB/s]
> Downloading:  27% 333M/1.22G [00:04<00:11, 76.0MB/s]
> Downloading:  28% 341M/1.22G [00:04<00:11, 76.0MB/s]
> Downloading:  29% 348M/1.22G [00:04<00:11, 76.1MB/s]
> Downloading:  29% 356M/1.22G [00:04<00:11, 76.3MB/s]
> Downloading:  30% 364M/1.22G [00:04<00:11, 76.4MB/s]
> Downloading:  31% 371M/1.22G [00:04<00:11, 76.4MB/s]
> Downloading:  31% 379M/1.22G [00:05<00:11, 75.5MB/s]
> Downloading:  32% 387M/1.22G [00:05<00:10, 76.0MB/s]
> Downloading:  32% 394M/1.22G [00:05<00:10, 76.0MB/s]
> Downloading:  33% 402M/1.22G [00:05<00:10, 76.1MB/s]
> Downloading:  34% 409M/1.22G [00:05<00:10, 76.1MB/s]
> Downloading:  34% 417M/1.22G [00:05<00:10, 76.1MB/s]
> Downloading:  35% 425M/1.22G [00:05<00:10, 76.2MB/s]
> Downloading:  36% 432M/1.22G [00:05<00:10, 76.1MB/s]
> Downloading:  36% 440M/1.22G [00:05<00:10, 76.2MB/s]
> Downloading:  37% 448M/1.22G [00:05<00:10, 76.2MB/s]
> Downloading:  37% 455M/1.22G [00:06<00:10, 75.5MB/s]
> Downloading:  38% 463M/1.22G [00:06<00:09, 75.9MB/s]
> Downloading:  39% 471M/1.22G [00:06<00:09, 76.0MB/s]
> Downloading:  39% 478M/1.22G [00:06<00:09, 75.6MB/s]
> Downloading:  40% 486M/1.22G [00:06<00:09, 75.7MB/s]
> Downloading:  41% 493M/1.22G [00:06<00:09, 75.2MB/s]
> Downloading:  41% 501M/1.22G [00:06<00:09, 75.5MB/s]
> Downloading:  42% 509M/1.22G [00:06<00:09, 75.7MB/s]
> Downloading:  42% 516M/1.22G [00:06<00:09, 75.8MB/s]
> Downloading:  43% 524M/1.22G [00:06<00:09, 76.1MB/s]
> Downloading:  44% 531M/1.22G [00:07<00:08, 76.2MB/s]
> Downloading:  44% 539M/1.22G [00:07<00:08, 76.0MB/s]
> Downloading:  45% 547M/1.22G [00:07<00:08, 76.3MB/s]
> Downloading:  46% 554M/1.22G [00:07<00:08, 76.5MB/s]
> Downloading:  46% 562M/1.22G [00:07<00:08, 76.3MB/s]
> Downloading:  47% 570M/1.22G [00:07<00:08, 76.3MB/s]
> Downloading:  47% 577M/1.22G [00:07<00:08, 76.2MB/s]
> Downloading:  48% 585M/1.22G [00:07<00:08, 76.2MB/s]
> Downloading:  49% 593M/1.22G [00:07<00:08, 76.1MB/s]
> Downloading:  49% 600M/1.22G [00:07<00:08, 76.3MB/s]
> Downloading:  50% 608M/1.22G [00:08<00:07, 76.4MB/s]
> Downloading:  51% 616M/1.22G [00:08<00:07, 76.3MB/s]
> Downloading:  51% 623M/1.22G [00:08<00:07, 76.2MB/s]
> Downloading:  52% 631M/1.22G [00:08<00:07, 76.1MB/s]
> Downloading:  53% 639M/1.22G [00:08<00:07, 76.3MB/s]
> Downloading:  53% 646M/1.22G [00:08<00:07, 76.2MB/s]
> Downloading:  54% 654M/1.22G [00:08<00:07, 76.2MB/s]
> Downloading:  54% 661M/1.22G [00:08<00:07, 75.9MB/s]
> Downloading:  55% 669M/1.22G [00:08<00:07, 75.5MB/s]
> Downloading:  56% 677M/1.22G [00:08<00:07, 75.1MB/s]
> Downloading:  56% 684M/1.22G [00:09<00:07, 74.9MB/s]
> Downloading:  57% 692M/1.22G [00:09<00:07, 74.9MB/s]
> Downloading:  58% 699M/1.22G [00:09<00:06, 75.4MB/s]
> Downloading:  58% 707M/1.22G [00:09<00:06, 75.5MB/s]
> Downloading:  59% 715M/1.22G [00:09<00:06, 75.8MB/s]
> Downloading:  59% 722M/1.22G [00:09<00:06, 75.8MB/s]
> Downloading:  60% 730M/1.22G [00:09<00:06, 75.9MB/s]
> Downloading:  61% 737M/1.22G [00:09<00:06, 75.8MB/s]
> Downloading:  61% 745M/1.22G [00:09<00:06, 76.0MB/s]
> Downloading:  62% 753M/1.22G [00:09<00:06, 76.0MB/s]
> Downloading:  63% 760M/1.22G [00:10<00:06, 73.9MB/s]
> Downloading:  63% 768M/1.22G [00:10<00:06, 72.1MB/s]
> Downloading:  64% 775M/1.22G [00:10<00:05, 73.5MB/s]
> Downloading:  64% 783M/1.22G [00:10<00:05, 74.3MB/s]
> Downloading:  65% 791M/1.22G [00:10<00:05, 75.0MB/s]
> Downloading:  66% 798M/1.22G [00:10<00:05, 75.3MB/s]
> Downloading:  66% 806M/1.22G [00:10<00:05, 75.4MB/s]
> Downloading:  67% 813M/1.22G [00:10<00:05, 75.8MB/s]
> Downloading:  68% 821M/1.22G [00:10<00:05, 75.9MB/s]
> Downloading:  68% 829M/1.22G [00:10<00:05, 75.9MB/s]
> Downloading:  69% 836M/1.22G [00:11<00:05, 75.9MB/s]
> Downloading:  69% 844M/1.22G [00:11<00:05, 74.3MB/s]
> Downloading:  70% 851M/1.22G [00:11<00:04, 74.9MB/s]
> Downloading:  71% 859M/1.22G [00:11<00:04, 75.3MB/s]
> Downloading:  71% 867M/1.22G [00:11<00:04, 75.6MB/s]
> Downloading:  72% 874M/1.22G [00:11<00:04, 75.8MB/s]
> Downloading:  73% 882M/1.22G [00:11<00:04, 76.0MB/s]
> Downloading:  73% 890M/1.22G [00:11<00:04, 76.2MB/s]
> Downloading:  74% 897M/1.22G [00:11<00:04, 76.4MB/s]
> Downloading:  74% 905M/1.22G [00:11<00:04, 76.5MB/s]
> Downloading:  75% 913M/1.22G [00:12<00:03, 76.7MB/s]
> Downloading:  76% 920M/1.22G [00:12<00:03, 76.2MB/s]
> Downloading:  76% 928M/1.22G [00:12<00:03, 76.4MB/s]
> Downloading:  77% 936M/1.22G [00:12<00:03, 76.6MB/s]
> Downloading:  78% 943M/1.22G [00:12<00:03, 76.6MB/s]
> Downloading:  78% 951M/1.22G [00:12<00:03, 76.7MB/s]
> Downloading:  79% 959M/1.22G [00:12<00:03, 76.8MB/s]
> Downloading:  79% 967M/1.22G [00:12<00:03, 76.9MB/s]
> Downloading:  80% 974M/1.22G [00:12<00:03, 77.1MB/s]
> Downloading:  81% 982M/1.22G [00:12<00:03, 77.0MB/s]
> Downloading:  81% 990M/1.22G [00:13<00:02, 77.0MB/s]
> Downloading:  82% 997M/1.22G [00:13<00:02, 76.8MB/s]
> Downloading:  83% 1.01G/1.22G [00:13<00:02, 76.8MB/s]
> Downloading:  83% 1.01G/1.22G [00:13<00:02, 76.7MB/s]
> Downloading:  84% 1.02G/1.22G [00:13<00:02, 76.7MB/s]
> Downloading:  85% 1.03G/1.22G [00:13<00:02, 76.8MB/s]
> Downloading:  85% 1.04G/1.22G [00:13<00:02, 76.7MB/s]
> Downloading:  86% 1.04G/1.22G [00:13<00:02, 76.6MB/s]
> Downloading:  86% 1.05G/1.22G [00:13<00:02, 76.7MB/s]
> Downloading:  87% 1.06G/1.22G [00:13<00:02, 76.8MB/s]
> Downloading:  88% 1.07G/1.22G [00:14<00:01, 76.7MB/s]
> Downloading:  88% 1.07G/1.22G [00:14<00:01, 76.8MB/s]
> Downloading:  89% 1.08G/1.22G [00:14<00:01, 76.3MB/s]
> Downloading:  90% 1.09G/1.22G [00:14<00:01, 75.9MB/s]
> Downloading:  90% 1.10G/1.22G [00:14<00:01, 76.1MB/s]
> Downloading:  91% 1.10G/1.22G [00:14<00:01, 76.3MB/s]
> Downloading:  91% 1.11G/1.22G [00:14<00:01, 76.3MB/s]
> Downloading:  92% 1.12G/1.22G [00:14<00:01, 76.5MB/s]
> Downloading:  93% 1.13G/1.22G [00:14<00:01, 76.6MB/s]
> Downloading:  93% 1.14G/1.22G [00:14<00:01, 76.5MB/s]
> Downloading:  94% 1.14G/1.22G [00:15<00:00, 76.3MB/s]
> Downloading:  95% 1.15G/1.22G [00:15<00:00, 76.4MB/s]
> Downloading:  95% 1.16G/1.22G [00:15<00:00, 75.6MB/s]
> Downloading:  96% 1.17G/1.22G [00:15<00:00, 73.1MB/s]
> Downloading:  96% 1.17G/1.22G [00:15<00:00, 71.9MB/s]
> Downloading:  97% 1.18G/1.22G [00:15<00:00, 73.3MB/s]
> Downloading:  98% 1.19G/1.22G [00:15<00:00, 74.4MB/s]
> Downloading:  98% 1.20G/1.22G [00:15<00:00, 74.9MB/s]
> Downloading:  99% 1.20G/1.22G [00:15<00:00, 75.4MB/s]
> Downloading: 100% 1.22G/1.22G [00:16<00:00, 75.7MB/s]
> Fetching 16 files:  25% 4/16 [00:17<01:12,  6.01s/it]
> Downloading: 100% 209/209 [00:00<00:00, 193kB/s]
> Fetching 16 files:  38% 6/16 [00:19<00:30,  3.01s/it]
> Downloading: 100% 592/592 [00:00<00:00, 586kB/s]
> Fetching 16 files:  44% 7/16 [00:19<00:20,  2.27s/it]
> Downloading:   0% 0.00/492M [00:00<?, ?B/s]
> Downloading:   1% 4.79M/492M [00:00<00:10, 47.9MB/s]
> Downloading:   3% 12.4M/492M [00:00<00:07, 64.4MB/s]
> Downloading:   4% 20.0M/492M [00:00<00:06, 69.8MB/s]
> Downloading:   6% 27.6M/492M [00:00<00:06, 72.3MB/s]
> Downloading:   7% 35.4M/492M [00:00<00:06, 74.1MB/s]
> Downloading:   9% 43.0M/492M [00:00<00:05, 74.9MB/s]
> Downloading:  10% 50.6M/492M [00:00<00:05, 75.2MB/s]
> Downloading:  12% 58.3M/492M [00:00<00:05, 75.7MB/s]
> Downloading:  13% 66.0M/492M [00:00<00:05, 76.1MB/s]
> Downloading:  15% 73.6M/492M [00:01<00:05, 76.3MB/s]
> Downloading:  17% 81.4M/492M [00:01<00:05, 76.7MB/s]
> Downloading:  18% 89.1M/492M [00:01<00:05, 76.5MB/s]
> Downloading:  20% 96.7M/492M [00:01<00:05, 76.4MB/s]
> Downloading:  21% 104M/492M [00:01<00:05, 76.5MB/s] 
> Downloading:  23% 112M/492M [00:01<00:04, 76.8MB/s]
> Downloading:  24% 120M/492M [00:01<00:04, 77.1MB/s]
> Downloading:  26% 128M/492M [00:01<00:04, 77.1MB/s]
> Downloading:  27% 135M/492M [00:01<00:04, 77.0MB/s]
> Downloading:  29% 143M/492M [00:01<00:04, 77.2MB/s]
> Downloading:  31% 151M/492M [00:02<00:04, 77.4MB/s]
> Downloading:  32% 159M/492M [00:02<00:04, 77.2MB/s]
> Downloading:  34% 166M/492M [00:02<00:04, 76.9MB/s]
> Downloading:  35% 174M/492M [00:02<00:04, 77.0MB/s]
> Downloading:  37% 182M/492M [00:02<00:04, 76.8MB/s]
> Downloading:  38% 189M/492M [00:02<00:03, 76.8MB/s]
> Downloading:  40% 197M/492M [00:02<00:03, 76.9MB/s]
> Downloading:  42% 205M/492M [00:02<00:03, 77.2MB/s]
> Downloading:  43% 213M/492M [00:02<00:03, 76.9MB/s]
> Downloading:  45% 220M/492M [00:02<00:03, 77.1MB/s]
> Downloading:  46% 228M/492M [00:03<00:03, 76.9MB/s]
> Downloading:  48% 236M/492M [00:03<00:03, 76.4MB/s]
> Downloading:  49% 244M/492M [00:03<00:03, 76.6MB/s]
> Downloading:  51% 251M/492M [00:03<00:03, 76.6MB/s]
> Downloading:  53% 259M/492M [00:03<00:03, 76.9MB/s]
> Downloading:  54% 267M/492M [00:03<00:02, 76.9MB/s]
> Downloading:  56% 274M/492M [00:03<00:02, 77.0MB/s]
> Downloading:  57% 282M/492M [00:03<00:02, 76.9MB/s]
> Downloading:  59% 290M/492M [00:03<00:02, 76.7MB/s]
> Downloading:  60% 297M/492M [00:03<00:02, 76.8MB/s]
> Downloading:  62% 305M/492M [00:04<00:02, 76.5MB/s]
> Downloading:  64% 313M/492M [00:04<00:02, 76.4MB/s]
> Downloading:  65% 321M/492M [00:04<00:02, 76.6MB/s]
> Downloading:  67% 328M/492M [00:04<00:02, 76.7MB/s]
> Downloading:  68% 336M/492M [00:04<00:02, 76.4MB/s]
> Downloading:  70% 344M/492M [00:04<00:01, 76.0MB/s]
> Downloading:  71% 351M/492M [00:04<00:01, 76.4MB/s]
> Downloading:  73% 359M/492M [00:04<00:01, 76.3MB/s]
> Downloading:  74% 366M/492M [00:04<00:01, 76.0MB/s]
> Downloading:  76% 374M/492M [00:04<00:01, 76.2MB/s]
> Downloading:  78% 382M/492M [00:05<00:01, 76.0MB/s]
> Downloading:  79% 389M/492M [00:05<00:01, 76.2MB/s]
> Downloading:  81% 397M/492M [00:05<00:01, 73.9MB/s]
> Downloading:  82% 405M/492M [00:05<00:01, 74.1MB/s]
> Downloading:  84% 412M/492M [00:05<00:01, 74.7MB/s]
> Downloading:  85% 420M/492M [00:05<00:00, 75.0MB/s]
> Downloading:  87% 427M/492M [00:05<00:00, 75.2MB/s]
> Downloading:  88% 435M/492M [00:05<00:00, 75.6MB/s]
> Downloading:  90% 442M/492M [00:05<00:00, 75.6MB/s]
> Downloading:  91% 450M/492M [00:05<00:00, 75.8MB/s]
> Downloading:  93% 458M/492M [00:06<00:00, 76.2MB/s]
> Downloading:  95% 465M/492M [00:06<00:00, 76.3MB/s]
> Downloading:  96% 473M/492M [00:06<00:00, 74.4MB/s]
> Downloading:  98% 481M/492M [00:06<00:00, 75.0MB/s]
> Downloading: 100% 492M/492M [00:06<00:00, 75.9MB/s]
> Fetching 16 files:  50% 8/16 [00:26<00:29,  3.71s/it]
> Downloading:   0% 0.00/525k [00:00<?, ?B/s]
> Downloading: 100% 525k/525k [00:00<00:00, 3.57MB/s]
> Fetching 16 files:  56% 9/16 [00:27<00:19,  2.81s/it]
> Downloading: 100% 472/472 [00:00<00:00, 408kB/s]
> Fetching 16 files:  62% 10/16 [00:28<00:12,  2.16s/it]
> Downloading: 100% 806/806 [00:00<00:00, 793kB/s]
> Fetching 16 files:  69% 11/16 [00:28<00:08,  1.70s/it]
> Downloading:   0% 0.00/1.06M [00:00<?, ?B/s]
> Downloading: 100% 1.06M/1.06M [00:00<00:00, 6.60MB/s]
> Fetching 16 files:  75% 12/16 [00:29<00:05,  1.44s/it]
> Downloading: 100% 743/743 [00:00<00:00, 641kB/s]
> Fetching 16 files:  81% 13/16 [00:30<00:03,  1.20s/it]
> Downloading:   0% 0.00/3.44G [00:00<?, ?B/s]
> ...
> Downloading: 100% 3.44G/3.44G [00:45<00:00, 75.0MB/s]
> Fetching 16 files:  88% 14/16 [01:16<00:29, 14.77s/it]
> Downloading: 100% 522/522 [00:00<00:00, 454kB/s]
> Fetching 16 files:  94% 15/16 [01:17<00:10, 10.53s/it]
> Downloading:   0% 0.00/335M [00:00<?, ?B/s]
> Downloading:   1% 4.71M/335M [00:00<00:07, 47.1MB/s]
> ...
> Downloading: 100% 335M/335M [00:04<00:00, 76.1MB/s]
> Fetching 16 files: 100% 16/16 [01:21<00:00,  5.12s/it]
> Generating class images: 100% 3/3 [00:28<00:00,  9.61s/it]
> Downloading: 100% 1.06M/1.06M [00:00<00:00, 6.61MB/s]
> ...
> Downloading: 100% 492M/492M [00:06<00:00, 75.7MB/s]
> Steps:   0% 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
>     args.func(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/drive/MyDrive/AI/DreamBooth/training_data/mike_pics_training_data', '--class_data_dir=/content/data/guy', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/sks', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of sks guy', '--class_prompt=photo of a guy', '--seed=1337', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=fp16', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=800']' died with <Signals.SIGABRT: 6>.
>

**Comment by TheLastBen** [comment] 2022-10-01 09:07
Thank you very much for the files, have you accepted the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4 ?

**Comment by TheLastBen** [comment] 2022-10-01 09:20
it looks like you missed the cell downloading the model

**Comment by liangwei191** [comment] 2022-10-01 11:33
I get a100 at first too after I found the cost drain too fast.So I use menu runtime->reset factory runtime to random a gpu until get a usable one.

**Comment by delbalso** [comment] 2022-10-01 13:53
> Thank you very much for the files, have you accepted the terms in https://huggingface.co/CompVis/stable-diffusion-v1-4 ?

Yep

> it looks like you missed the cell downloading the model

Why do you think that? In any case, I just downloaded it again.

I noticed that I copied the precompiled files wrong, but have now fixed them.

BTW the `%%capture` thing confused me because I didn't see an error.

Here's an update to the error I'm getting:

> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:99: UserWarning: /usr/lib64-nvidia did not contain libcudart.so as expected! Searching further paths...
>   f'{candidate_env_vars["LD_LIBRARY_PATH"]} did not contain '
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('6000,"kernelManagerProxyHost"'), PosixPath('"172.28.0.3","jupyterArgs"'), PosixPath('"/usr/local/bin/dap_multiplexer","enableLsp"'), PosixPath('["--ip=172.28.0.2"],"debugAdapterMultiplexerPath"'), PosixPath('true}'), PosixPath('{"kernelManagerProxyPort"')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('//ipykernel.pylab.backend_inline'), PosixPath('module')}
>   "WARNING: The following directories listed in your path were found to "
> /usr/local/lib/python3.7/dist-packages/bitsandbytes/cuda_setup/paths.py:21: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/env/python')}
>   "WARNING: The following directories listed in your path were found to "
> CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
> CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
> CUDA SETUP: Highest compute capability among GPUs detected: 8.0
> CUDA SETUP: Detected CUDA version 111
> CUDA SETUP: Loading binary /usr/local/lib/python3.7/dist-packages/bitsandbytes/libbitsandbytes_cuda111.so...
> Steps:   0% 2/2000 [00:05<1:14:31,  2.24s/it, loss=0.42, lr=5e-6]  Traceback (most recent call last):
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 606, in <module>
>     main()
>   File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 550, in main
>     noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/utils/operations.py", line 507, in __call__
>     return convert_to_fp32(self.model_forward(*args, **kwargs))
>   File "/usr/local/lib/python3.7/dist-packages/torch/amp/autocast_mode.py", line 12, in decorate_autocast
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_condition.py", line 262, in forward
>     sample = self.mid_block(sample, emb, encoder_hidden_states=encoder_hidden_states)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_blocks.py", line 375, in forward
>     hidden_states = attn(hidden_states, encoder_hidden_states)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 167, in forward
>     hidden_states = block(hidden_states, context=context)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 219, in forward
>     hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 451, in forward
>     return self.net(hidden_states)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/container.py", line 139, in forward
>     input = module(input)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 114, in forward
>     return F.linear(input, self.weight, self.bias)
> RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`
> Steps:   0% 2/2000 [00:05<1:36:41,  2.90s/it, loss=0.42, lr=5e-6]
> Traceback (most recent call last):
>   File "/usr/local/bin/accelerate", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
>     args.func(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
>     simple_launcher(args)
>   File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
>     raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
> subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--pretrained_model_name_or_path=/content/gdrive/MyDrive/stable-diffusion-v1-4', '--instance_data_dir=/content/data/mikemdb', '--output_dir=/content/models/mikemdb', '--instance_prompt=photo of mikemdb man', '--seed=12345', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=2000']' returned non-zero exit status 1.

Any ideas?

**Comment by TheLastBen** [comment] 2022-10-01 13:59
If you're using the A100, I still didn't implement them in the colab, yet, I'll do it shortly

**Comment by delbalso** [comment] 2022-10-01 14:04
Yes I understand, I just placed the files in the right place manually.

FYI think I just got it working by killing
> --use_8bit_adam \
and 
> --mixed_precision="fp16" \

**Comment by delbalso** [comment] 2022-10-01 14:06
How long does training take on other GPUs? It looks like 2000 steps on 512 resolution on an A100 on colab takes 30 mins

**Comment by TheLastBen** [comment] 2022-10-01 14:07
it's because you removed the --use_8bit_adam \ and --mixed_precision="fp16" \
make sure they are the cause for the error you're getting

**Comment by TheLastBen** [comment] 2022-10-01 14:07
try leaving the --mixed_precision="fp16" \

**Comment by delbalso** [comment] 2022-10-01 14:40
I'm saying it only started working when I removed `--mixed_precision="fp16" \`

**Comment by delbalso** [comment] 2022-10-01 14:56
Should I set `train_batch_size` to the number of training instances I have?

**Comment by TheLastBen** [comment] 2022-10-01 14:58
That is the number of models of the same instance it trains, best to keep it to one to save time

**Comment by delbalso** [comment] 2022-10-01 15:03
Thank you

**Comment by ackl** [comment] 2022-10-03 17:34
i'm not sure if this issue should've been closed without making some changes in the notebooks? I have run into the exact same issue today, got an A100 and during training it would throw the same `CUBLAS_STATUS_EXECUTION_FAILED` error right as it gets to step 2

I also resolved it by removing `--mixed_precision="fp16" \`

**Comment by TheLastBen** [comment] 2022-10-03 18:22
@ackl I'll make sure A100 users won't face that issue in the future

**Comment by TheLastBen** [comment] 2022-10-03 19:00
I have fixed the precision issue for A100s, waiting for your confirmation to close the issue. Make sure you use the updated Colab Notebook

**Comment by ackl** [comment] 2022-10-03 19:40
I can confirm it works with the latest commit that uses `--mixed_precision="no"` when GPU == A100. Thanks for the quick update!

**Comment by TheLastBen** [comment] 2022-10-03 19:41
Thanks for the feedback

**Closed by TheLastBen** 2022-10-03 19:41 UTC
