### ISSUE TITLE
 OSError: /content/stable-diffusion-V2 does not appear to have a file named preprocessor_config.json. 

### ISSUE THREAD

**Issue by Tylersuard** [TheLastBen/fast-stable-diffusion#1097] opened 2022-12-21 00:08 UTC
This occurs when trying to load model V2.1-512, during the model download cell.

**Comment by Daviljoe193** [comment] 2022-12-21 01:16
Totally broken here past that for me. Tried training on the 768 model, and it got as far as training the text encoder, before an error flashed in the output, which unfortunately gets cleared just before unet training starts, and unet training errors out with the following.

`Training the UNet...
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 517, in main
    text_encoder = CLIPTextModel.from_pretrained(args.output_dir, subfolder="text_encoder_trained")
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1966, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/configuration_clip.py", line 133, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /content/models/gvgtgm does not appear to have a file named text_encoder_trained/config.json. Checkout 'https://huggingface.co//content/models/gvgtgm/None' for available files.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/gvgtgm', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-768', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/gvgtgm/instance_images', '--output_dir=/content/models/gvgtgm', '--instance_prompt=', '--seed=440229', '--resolution=768', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-6', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=2400']' returned non-zero exit status 1.
Something went wrong`

**Comment by Daviljoe193** [comment] 2022-12-21 02:07
For now, there's a (Very ugly, but functional) workaround. Load the 2.1 model as a custom model, choosing the model version from Custom_Model_Version, and linking to the CKPT on Huggingface.

**Comment by K1NGC0BRA100** [comment] 2022-12-21 02:38
> For now, there's a (Very ugly, but functional) workaround. Load the 2.1 model as a custom model, choosing the model version from Custom_Model_Version, and setting CKPT_Link to the CKPT on Huggingface.

How exactly do you do that? I cant find this custom model version you are talking about and every time a past the link it says wrong link. Btw, it doesnt matter what version I load the problem is there regardless

**Comment by Daviljoe193** [comment] 2022-12-21 02:47
> > For now, there's a (Very ugly, but functional) workaround. Load the 2.1 model as a custom model, choosing the model version from Custom_Model_Version, and setting CKPT_Link to the CKPT on Huggingface.
> 
> How exactly do you do that? I cant find this custom model version you are talking about and every time a past the link it says wrong link. Btw, it doesnt matter what version I load the problem is there regardless

![gitproof](https://user-images.githubusercontent.com/67191631/208808710-8be4916d-1f5d-496c-a119-0dc6dec74dbd.jpg)

**Comment by brandonkoch3** [comment] 2022-12-21 04:03
Also noting the same issue as @Daviljoe193.  In my case, setting the direct link to the CKPT file on HuggingFace (for example the v2-1_768-nonema-pruned.ckpt) results in a model mismatch error when trying to load the model.  Not sure if there's anything else to try, or if further investigation needs to be done as to what changed on the model-side that broke this tool.

**Comment by TheLastBen** [comment] 2022-12-21 05:17
which notebook ? A1111 or Dreambooth ?

**Comment by K1NGC0BRA100** [comment] 2022-12-21 05:27
A1111

**Comment by brandonkoch3** [comment] 2022-12-21 05:47
> which notebook ? A1111 or Dreambooth ?

I’m having the issue with Dreambooth, as related to the missing `config.json` file.

**Comment by TheLastBen** [comment] 2022-12-21 06:23
use the latest colab, the v2 should work/convert without issues

**Comment by brandonkoch3** [comment] 2022-12-21 06:26
> use the latest colab, the v2 should work/convert without issues

Does this apply to v2.1 or only v2?

**Comment by TheLastBen** [comment] 2022-12-21 06:48
I didn't change the colab in that area recently, but it's better to always use the link to get the updates : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast-DreamBooth.ipynb

**Comment by brandonkoch3** [comment] 2022-12-21 06:55
Thanks for your reply (and the awesome notebook, by the way).  I checked the commit history and it didn’t seem like anything changed on your side, but it definitely seemed like the latest commit from StabilityAI on the 2.1-768 and 2.1-512 models did something that broke the “training” part of the Colab.  I’ve been using your script with v2.1-768 for a few days without issue, up until this morning, when it stopped working using the same steps of *not* choosing a custom model and selecting the v2.1-768 from the drop-down, and training.  Definitely seems like something on the StabilityAI side broke it, unless it’s just a me problem.

**Comment by Daviljoe193** [comment] 2022-12-21 06:56
> Thanks for your reply (and the awesome notebook, by the way). I checked the commit history and it didn’t seem like anything changed on your side, but it definitely seemed like the latest commit from StabilityAI on the 2.1-768 and 2.1-512 models did something that broke the “training” part of the Colab. I’ve been using your script with v2.1-768 for a few days without issue, up until this morning, when it stopped working using the same steps of _not_ choosing a custom model and selecting the v2.1-768 from the drop-down, and training. Definitely seems like something on the StabilityAI side broke it, unless it’s just a me problem.

It ain't a you problem, without the workaround I mentioned, I couldn't get through the training cell either.

**Comment by Kpenciler** [comment] 2022-12-21 06:57
I have the same symptoms. The latest version is not saving the model properly and does not work correctly (2.1-512 models).
<img width="692" alt="スクリーンショット 2022-12-21 15 54 57" src="https://user-images.githubusercontent.com/79185244/208840524-f663d87a-e2d6-4566-a9a7-217b3af2b74b.png">

**Comment by Kpenciler** [comment] 2022-12-21 07:10
@Daviljoe193
I was able to load the model using your excellent method, but the subsequent execution of convertodiff.py does not work.
"Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False."

Can you please let me know if this has been resolved?

**Comment by TheLastBen** [comment] 2022-12-21 07:22
> I have the same symptoms. The latest version is not saving the model properly and does not work correctly (2.1-512 models).
> <img alt="スクリーンショット 2022-12-21 15 54 57" width="692" src="https://user-images.githubusercontent.com/79185244/208840524-f663d87a-e2d6-4566-a9a7-217b3af2b74b.png">

you didn't upload instance images

**Comment by Kpenciler** [comment] 2022-12-21 07:30
@TheLastBen
Thanks for the advice.
I will check it out and get the code working.

**Comment by dalmackay** [comment] 2022-12-21 09:18
Just got this too, with updated repo from github link

```
Training the UNet...
Traceback (most recent call last):
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 517, in main
    text_encoder = CLIPTextModel.from_pretrained(args.output_dir, subfolder="text_encoder_trained")
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 1966, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/configuration_clip.py", line 133, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 559, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/configuration_utils.py", line 614, in _get_config_dict
    resolved_config_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /content/models/dallinmackay1 does not appear to have a file named text_encoder_trained/config.json. Checkout 'https://huggingface.co//content/models/dallinmackay1/None' for available files.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--image_captions_filename', '--train_only_unet', '--save_starting_step=500', '--save_n_steps=0', '--Session_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/dallinmackay1', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-768', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/dallinmackay1/instance_images', '--output_dir=/content/models/dallinmackay1', '--instance_prompt=', '--seed=70364', '--resolution=768', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=2800']' returned non-zero exit status 1.
Something went wrong
```

**Comment by TheLastBen** [comment] 2022-12-21 09:53
remove the folder `/content/models/dallinmackay1/text_encoder_trained`

**Comment by einacio** [comment] 2022-12-21 10:12
I also get the config.json error.

disabling the unet training to see the text_encoder error I see this

```
File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 852, in <module>
    main()
  File "/content/diffusers/examples/dreambooth/train_dreambooth.py", line 804, in main
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 641, in from_pretrained
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 306, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 402, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /content/stable-diffusion-v2-512 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//content/stable-diffusion-v2-512/None' for available files.
Progress:|█████████████████████████|100% 150/150 [03:18<00:00,  1.32s/it, loss=0.151, lr=1e-7]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/content/diffusers/examples/dreambooth/train_dreambooth.py', '--train_only_text_encoder', '--image_captions_filename', '--train_text_encoder', '--dump_only_text_encoder', '--pretrained_model_name_or_path=/content/stable-diffusion-v2-512', '--instance_data_dir=/content/gdrive/MyDrive/Fast-Dreambooth/Sessions/su/instance_images', '--output_dir=/content/models/su', '--instance_prompt=', '--seed=828101', '--resolution=512', '--mixed_precision=fp16', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=2e-06', '--lr_scheduler=polynomial', '--lr_warmup_steps=0', '--max_train_steps=150']' returned non-zero exit status 1.
Something went wrong
```

it looks like the folder structure for stable-diffusion changed and a file is in a different path

**Comment by einacio** [comment] 2022-12-21 10:39
this line should be updated

```
!echo -e "scheduler\ntext_encoder\ntokenizer\nunet\nvae\nmodel_index.json" > .git/info/sparse-checkout
```

to 
```
!echo -e "scheduler\ntext_encoder\ntokenizer\nunet\nvae\nfeature_extractor\nmodel_index.json" > .git/info/sparse-checkout
```

also i'd say `git pull --depth 1` should reduce a little the time and space used when downloading the model.

I could make a PR later, but I don't have time at the moment

**Comment by FabioCastilho** [comment] 2022-12-21 16:29
Hello, to solve this problem, just create a folder named feature_extractor inside stable-diffusion-v2-512 and put the preprocessor_config file that is on the https://huggingface.co/stabilityai/stable-diffusion-2-1-base page /tree/main
![image](https://user-images.githubusercontent.com/21134162/208955516-da3f0296-4041-428f-9fe4-d7c8ed86972c.png)
![image](https://user-images.githubusercontent.com/21134162/208955611-febdfdd0-229b-4f6a-aeae-4ef5aa1c514b.png)

**Comment by TheLastBen** [comment] 2022-12-21 16:50
it fixed in the latest commit, just update the colab and you won't face the issue anymore

**Comment by riderx** [comment] 2022-12-21 18:56
i found out custom model was not necessary in v2
![CleanShot 2022-12-22 at 02 55 33@2x](https://user-images.githubusercontent.com/4084527/208982157-348f5fa7-5b04-4f1a-9bfb-1f4ff9e11357.png)
this text lead me to think it's needed, but in the code i saw it wasn't.
now i have normal output

**Comment by jvoxel** [comment] 2022-12-22 00:25
I have this error trying to download V2.1 768 model on the A1111 notebook 
And if I manually download with wget and put the model and the .yaml in my drive the colab runs out of memory and gradio can't launch on T4 it used to work fine a week ago
```
Converting to CKPT ...
The config attributes {'upcast_attention': True} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Traceback (most recent call last):
  File "/content/convertosdv2.py", line 1107, in <module>
    convert(args)
  File "/content/convertosdv2.py", line 1058, in convert
    pipe = StableDiffusionPipeline.from_pretrained(args.model_to_load, torch_dtype=load_dtype, tokenizer=None, safety_checker=None)
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 661, in from_pretrained
    loaded_sub_model = load_method(cached_folder, **loading_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 306, in from_pretrained
    feature_extractor_dict, kwargs = cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/feature_extraction_utils.py", line 402, in get_feature_extractor_dict
    resolved_feature_extractor_file = cached_file(
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: /content/stable-diffusion-V2 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//content/stable-diffusion-V2/None' for available files.
Something went wrong, try again 
```

**Comment by jvoxel** [comment] 2022-12-22 00:37
> Hello, to solve this problem, just create a folder named feature_extractor inside stable-diffusion-v2-512 and put the preprocessor_config file that is on the https://huggingface.co/stabilityai/stable-diffusion-2-1-base page /tree/main ![image](https://user-images.githubusercontent.com/21134162/208955516-da3f0296-4041-428f-9fe4-d7c8ed86972c.png) ![image](https://user-images.githubusercontent.com/21134162/208955611-febdfdd0-229b-4f6a-aeae-4ef5aa1c514b.png)

that worked thanks broda

**Comment by K1NGC0BRA100** [comment] 2022-12-22 03:07
> 

Would you mind showing me exactly how to do that? I have zero understanding of huggingface. Im just trying to get StableDiffusion to work on my laptop

**Comment by CJohnDesign** [comment] 2022-12-22 05:30
> > > For now, there's a (Very ugly, but functional) workaround. Load the 2.1 model as a custom model, choosing the model version from Custom_Model_Version, and setting CKPT_Link to the CKPT on Huggingface.
> > 
> > 
> > How exactly do you do that? I cant find this custom model version you are talking about and every time a past the link it says wrong link. Btw, it doesnt matter what version I load the problem is there regardless
> 
> ![gitproof](https://user-images.githubusercontent.com/67191631/208808710-8be4916d-1f5d-496c-a119-0dc6dec74dbd.jpg)
> 
> The link needs to be a resolve/main link,not a blob/main link.
> 
> edit: I just realised this issue probably affects more than just the Dreambooth notebook. This is what you'd change for the Auto1111 notebook.
> 
> ![moreproof-fix](https://user-images.githubusercontent.com/67191631/208811676-f9a4460d-7e05-4ac7-8ff0-81cff4fd9138.jpg)

This worked for me - thanks

URL: `https://huggingface.co/stabilityai/stable-diffusion-2-1/resolve/main/v2-1_768-ema-pruned.ckpt`

**Comment by riderx** [comment] 2022-12-22 15:56
For info today the website huggingface.co/ was not accessible multiple time for me, so that could be the issue

**Comment by brandonkoch3** [comment] 2022-12-22 16:18
> it fixed in the latest commit, just update the colab and you won't face the issue anymore

Confirming that the latest commit resolved the issue for me during testing yesterday.  Will follow-up if any additional issues arise.  Thank you for the help!

**Comment by ozunaltun** [comment] 2022-12-22 20:11
still having the same issue on AUTOMATIC1111

**Comment by oneheartforone** [comment] 2023-04-15 08:38
> Hello, to solve this problem, just create a folder named feature_extractor inside stable-diffusion-v2-512 and put the preprocessor_config file that is on the https://huggingface.co/stabilityai/stable-diffusion-2-1-base page /tree/main ![image](https://user-images.githubusercontent.com/21134162/208955516-da3f0296-4041-428f-9fe4-d7c8ed86972c.png) ![image](https://user-images.githubusercontent.com/21134162/208955611-febdfdd0-229b-4f6a-aeae-4ef5aa1c514b.png)

sloved my question.

**Comment by chen-si-jia** [comment] 2023-09-13 07:34
> Hello, to solve this problem, just create a folder named feature_extractor inside stable-diffusion-v2-512 and put the preprocessor_config file that is on the https://huggingface.co/stabilityai/stable-diffusion-2-1-base page /tree/main ![image](https://user-images.githubusercontent.com/21134162/208955516-da3f0296-4041-428f-9fe4-d7c8ed86972c.png) ![image](https://user-images.githubusercontent.com/21134162/208955611-febdfdd0-229b-4f6a-aeae-4ef5aa1c514b.png)

Thank you. Your reply had resolved my question.

**Closed** 2023-09-13 09:32 UTC
